apiVersion: v1
kind: ConfigMap
metadata:
  name: ibm-odf-job-config
data:
  install-odf.sh: |
    #!/bin/bash

    ibmcloud config --check-version=false
    ibmcloud api https://cloud.ibm.com
    ibmcloud target -r $REGION
    ibmcloud login --apikey $IBMCLOUD_API_KEY

    ibmcloud plugin install kubernetes-service -f

    export OCP_VERSION="${ibmcloud ks cluster get -c $CLUSTER --output json | jq -r ".masterKubeVersion" | cut -d. -f-2}"

    ibmcloud oc cluster addon enable openshift-data-foundation -c $CLUSTER --version "${OCP_VERSION}.0"

